# version: '3.9'

services:
  web:
    build: .
    ports:
      - "5000:3000"
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app
    networks:
      - app-network

  mongo:
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network
    logging:
      driver: none

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
